# Generated by Django 5.2.7 on 2026-02-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Группа',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Дисциплина',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255, verbose_name='Название дисциплины')),
            ],
        ),
        migrations.CreateModel(
            name='Кафедра',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255, verbose_name='Название кафедры')),
            ],
        ),
        migrations.CreateModel(
            name='Преподаватель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фио', models.CharField(max_length=255, verbose_name='ФИО преподавателя')),
                ('кафедра', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='ПроверкаЗнаний',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('профиль', models.CharField(max_length=255, verbose_name='Профиль подготовки')),
                ('дата_проведения', models.DateField(verbose_name='Дата проведения')),
                ('время_проведения', models.TimeField(verbose_name='Время проведения')),
                ('группа', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.группа')),
                ('дисциплина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.дисциплина')),
                ('преподаватель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.преподаватель')),
            ],
        ),
    ]
